services:
  webhook:
    build: ./adh-webhook
    container_name: webhook
    ports:
      - "8000:8000"
    environment:
      - PORT=${PORT}
      - ADDR=${ADDR}
      - LOG_LEVEL=${LOG_LEVEL}
      - REDIS_ADDR=${REDIS_ADDR}
      - REDIS_PORT=${REDIS_PORT}
      - SECRET_KEY=${SECRET_KEY}
    depends_on:
      - redis
    volumes:
      - ./adh-webhook/logs:/var/log/webhook

  dashboard:
    build: ./adh-dashboard
    container_name: dashboard
    ports:
      - "3000:3000"
    environment:
      - REDIS_URL=${REDIS_URL}
      - USER_ID=${USER_ID}
      - USER_NAME=${USER_NAME}
      - USER_PASSWORD=${USER_PASSWORD}
    depends_on:
      redis:
        condition: service_healthy
    volumes:
      - ./adh-dashboard/logs:/var/log/dashboard

  redis:
    image: redis:7.4.2-alpine
    container_name: redis
    command: >
      redis-server
      --maxclients 10000
      --tcp-keepalive 300
      --timeout 0
      --lazyfree-lazy-expire yes
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  redis_data:
    driver: local
